# Using Node.js 16 as the base image
image: node:16

# Cache dependencies between builds
cache:
  paths:
    - node_modules/

# Define the stages of the CI/CD pipeline
stages:
  - build
  - deploy

# Building the application
build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - build/

# Deploying to GitLab Pages
pages:
  stage: deploy
  script:
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main  # Only deploy when changes are pushed to the main branch